name: Build

on:
  pull_request:
  push:
    branches: '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
		needs: lint

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

			- run: npm ci
			- run: npm run build
